# Generated by Django 3.2.13 on 2022-06-03 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailComponent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=70)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Email Components',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hierarchy_level', models.IntegerField()),
                ('parent_name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.components')),
            ],
            options={
                'verbose_name_plural': 'Components',
            },
        ),
    ]
