version: '3.9'
   
services:  
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
  app:
    build: 
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py loaddata ecomm_data.json &&
             python manage.py superuserinit &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - EMAIL_HOST_PASSWORD=wlsvozmozuwhyrio
      - EMAIL_HOST_USER=vietaodaiwebapp@gmail.com
    depends_on:
      - db