# Generated by Django 3.2.13 on 2022-06-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('ref_id', models.CharField(editable=False, max_length=128, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('undiscounted_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('billing_address', models.ForeignKey(blank=True, limit_choices_to=models.Q(('date_deleted__isnull', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_billing', to='account.address')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('order_type', models.ForeignKey(limit_choices_to=models.Q(('date_deleted__isnull', True), ('parent_name__in', ['Order Type'])), on_delete=django.db.models.deletion.CASCADE, to='ecommerce.attribute')),
                ('shipping_address', models.ForeignKey(blank=True, limit_choices_to=models.Q(('date_deleted__isnull', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_shipping', to='account.address')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('code', models.CharField(max_length=220, unique=True)),
                ('amount', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('status', models.ForeignKey(limit_choices_to=models.Q(('date_deleted__isnull', True), ('parent_name__in', ['Order Status'])), on_delete=django.db.models.deletion.CASCADE, to='ecommerce.attribute')),
            ],
            options={
                'verbose_name_plural': 'Order Status',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('SKU', models.ForeignKey(db_column='SKU', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.itemsinventory', to_field='SKU')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.voucher'),
        ),
    ]
