# Generated by Django 3.2.13 on 2022-05-22 02:19

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hierarchy_level', models.IntegerField()),
                ('parent_name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('is_filtered', models.BooleanField()),
                ('presentation', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', limit_choices_to={'hierarchy_level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hierarchy_level', models.IntegerField()),
                ('parent_name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('slug_url', models.SlugField(editable=False)),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', limit_choices_to={'hierarchy_level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(editable=False)),
                ('details', models.TextField()),
                ('description', models.TextField()),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('images', models.FileField(upload_to=ecommerce.models.item_dir_url)),
                ('category', models.ForeignKey(limit_choices_to={'hierarchy_level': 2}, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsInventory',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('SKU', models.CharField(editable=False, max_length=20, unique=True)),
                ('quantity', models.IntegerField()),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('color', models.ForeignKey(limit_choices_to=models.Q(('date_deleted__isnull', True), ('parent_name__in', ['Color', 'Colors']), ('is_filtered', True)), on_delete=django.db.models.deletion.CASCADE, related_name='attribute_color', to='ecommerce.attribute')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.item')),
                ('size', models.ForeignKey(limit_choices_to=models.Q(('date_deleted__isnull', True), ('parent_name__in', ['Size', 'Sizes']), ('is_filtered', True)), on_delete=django.db.models.deletion.CASCADE, related_name='attribute_size', to='ecommerce.attribute')),
            ],
            options={
                'verbose_name_plural': 'Items Inventories',
            },
        ),
        migrations.CreateModel(
            name='ItemsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_slug', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('images_url', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('images', models.FileField(upload_to=ecommerce.models.itemimages_dir_url)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.item')),
            ],
            options={
                'verbose_name_plural': 'Items Images',
            },
        ),
    ]
